### ISSUE TITLE
RFP: GovNERD(s) 

### ISSUE THREAD

**Issue by oplavande** [ethereum-optimism/ecosystem-contributions#109]
## Foundation **Mission Request - GovNERD(s)**

**Foundation Mission Summary:** The Foundation will experiment with the introduction of govNERDs to improve governance accessibility by shepherding proposals through the feedback, approval, and voting process. The initial experiment will span the Reflection Period, running from September 28th - November 15th. If successful, an additional Mission Request for a similar Mission may be posted ahead of Season 5.  

**S4 [Intent](https://gov.optimism.io/t/collective-intents/5874):** Governance accessibility 

**Proposal [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877):** Ember  

**Baseline grant amount:** 3,000 OP per GovNERD

**Should this Foundation Mission be fulfilled by one or multiple applicants:** Up to 2

**OP Labs or Optimism Foundation Sponsor:** @justine-hy 

**Submit by:** Sept 18th at 23:59 GMT 

**Selection by:** Sept 21st at 23:59 GMT 

**Start date:** September 21st (beginning of Reflection Period) 

**Completion date:** November 15th (end of Reflection Period)  

**Foundation Point of Contact:** @justine-hy and @Nicca42 

---

### **How will this Foundation Mission Request help accomplish the above Intent?**

The iterative nature of Optimism governance means it is constantly changing. While this should ultimately lead to improvements in the health of the overall governance system, it makes the system harder to navigate and has lowered accessibility of Optimism governance. The Foundation would like to experiment with govNERDs, who would shepherd proposals through the feedback, approval, and voting process while ensuring the forum is a place for the highest quality engagement. This should improve governance accessibility by making it easier for proposers to effectively navigate the proposal process and for delegates to find the high quality proposals that require their attention. 

### **What is required to execute this Foundation Mission Request?**

govNERDs will serve as neutral shepherds that ensure high quality governance proposals move through the proposal process successfully, taking over some important administrative work the Optimism Foundation has thus far fulfilled.

***General Governance Process:*** 

- Ensure delegates understand relevant processes during the upcoming Reflection Period, clarifying any ambiguities in documentation
- Attend delegate community calls to identify and clarify areas of confusion about the Reflection Period process
- Maintain the public governance calendar during the Reflection Period, updating and circulating as needed

 ***Proposal Feedback Process:***  

- Ensure all Reflection Period proposals follow templates, gathering feedback on templates and suggesting improvements to the Optimism Foundation
- Address any inconsistencies or non-compliance in proposals
- Identify where there is overlap in proposals and help proposers reduce overlap or collaborate (may not be relevant during the Reflection Period)
- Facilitate timely feedback from delegates on high quality proposals

***Proposal Approval Process:*** 

- Facilitate the review of proposals that require approvals by delegates in advance of the deadline required to move to a vote

***Proposal Voting Process:***  

- Alert delegates to the start and end of Special Voting Cycles and any other deadlines during the Reflection Period
- Manage Voting Cycle Roundups, adding approved proposals to the roundup before the deadline
- Ensure delegates understand what they need to be voting on throughout the Reflection Period

***Forum Management:*** 

- Monitor, manage, and reduce low quality forum engagement during the Reflection Period
- Manage discourse tags to aid discoverability of relevant proposals during the Reflection Period
- Flag important posts and/or comments to the Optimism Foundation

### **How should the Foundation measure progress towards this Mission?**  

- If this Mission is successful, the Foundation should be able to remove its role in the following functions:
    - Maintenance of the public governance calendar during the Reflection Period
    - Procedural questions raised in delegate community calls
    - Announcements to delegates pertaining to voting cycles or general governance schedules (without a corresponding decrease in number of delegates voting per proposal)
    - Alerts related to proposals receiving enough approvals to move to a vote, when required
    - Publication of Voting Cycle Roundups
- Reduction in forum spam, as measured by the number of forum issues the Foundation is asked to address

### **How should badgeholders measure impact upon completion of this Mission?** 

- The Foundation will circulate a survey for delegates to fill out regarding the level of clarity about the proposal process before and after this Reflection Period
- The Foundation will document any positive or negative feedback from delegates interacting with govNERDs throughout the Reflection Period and share a summary
- An increase in delegate participation among the top 100 delegates during this Reflection Period relative to the previous Reflection Period

---
## **Application Instructions:**

To apply for this Mission Request, please complete the form below and submit as a comment on this issue thread. Submissions will be open until Sep 18th 2023 23:59 GMT, at which time the Foundation will review all submissions and select *up to two applicants.* 

Copy the entire application below and leave a comment on this issue with your answers completed. A representative from the Optimism Foundation may reach out using the contact info provided to request more information as necessary.

<details>
  <summary>Application template</summary>

- **Applicant:**
- **Contact info:** Please specify the best point of contact (email preferred)
- **L2 recipient address:**
- **Please verify that you meet the qualifications for submitting at the above [[Tier](https://gov.optimism.io/t/collective-trust-tiers/5877)](https://gov.optimism.io/t/collective-trust-tiers/5877):**
- **Please acknowledge that you will need to complete a KYC process to receive this grant:**
- **Please link to any relevant previous work:**

---

**What makes you best-suited to execute this Mission? Please consider any experience relevant to the above requirements:** 

- [...]
- [...]

**Please explain your familiarity with Optimism Governance and the proposal process:** 

- [...]
- [...]

**Please describe the impact you aim to make in completing this Mission:**

- [...]

**Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833)] that should be used to determine whether you’ve executed on this proposal. Make sure you understand what a critical milestone is before answering this question:** 

- [...]

**Please verify that you are able to commit up to 8 hours per week to this role:**

- [...]

**Grants are awarded in OP, locked for one year. Please acknowledge that you are aware of the grant policies [link]**  

- [...]

**Please list any additional support you would require to execute this mission (financial, technical, etc.):**

- [...]

**Comment by govguide** [comment]
Hi Justine,

would you mind giving this RFP the status "Open" and adding it to the [Optimism Ecosystem Contributions 🔴✨ Project board]( https://github.com/orgs/ethereum-optimism/projects/31/views/1) where all the other RFPs are listed? 

This is relevant because there are some pages, including the Optimism Docs and for example [optimismgrants.io](https://optimismgrants.io), linking to the Project Board, which now doesn't show all RFPs anymore. Thanks!

**Comment by JeanGuillemont** [comment]
Sad i won't be available from 21/09, it looks like an amazing challenge !

**Comment by Dhannte** [comment]
**Applicant:** Gonna.eth
**Contact info:** gdhannte@gmail.com
**L2 recipient address:** 0xDCF7bE2ff93E1a7671724598b1526F3A33B1eC25
**Please verify that you meet the qualifications for submitting at the above:** I am Phoenix Tier
**Please acknowledge that you will need to complete a KYC process to receive this grant:** Yes.
**Please link to any relevant previous work:** Delgate since gov inception, a Grants council member since its inception. EthernautDAO co-founder

**What makes you best suited to execute this Mission? Please consider any experience relevant to the above requirements:**
I applied 3 times for a grant with EthernautDAO, then moved on to being part of the first committed, later participated in the grants council and ran operations on the last grants council. I'm also the host of the citizen's monthly call, EthernautDAO was a recipient of the first and second RPGFs and I've been a citizen since RPGF2. All this background gives me a deep understanding of how OP gov works and I'll be happy to guide anyone who needs it. 


**Please explain your familiarity with Optimism Governance and the proposal process:**
Applied to a grant on the first 3 cycles of OP gov. Voted in every cycle as a delegate, gave my delegate approval since I was able in Cycle 13 to missions, and worked on grant proposals structure since Cycle 10.

**Please describe the impact you aim to make in completing this Mission:**
I've been guiding people in the forum since [June 2022](https://gov.optimism.io/t/gf-phase-0-proposal-uniswap/2133/3?u=gonna.eth). I will continue to do so because it makes new users feel part of the collective, develops a rapport with the governance, and has a very positive impact. My aim now is to make sure the Foundation can entrust some of the workloads like calendar, updates, proposal approval tracking, and roundups publication to govNerds and open up some of their time bandwidth to design the next experimental steps.

**Please define the [[critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833)]([https://gov.optimism.io/t/grant-policies/5833) that](https://gov.optimism.io/t/grant-policies/5833)%C2%A0that) should be used to determine whether you’ve executed on this proposal. Make sure you understand what a critical milestone is before answering this question:**

Daily:
* Check the calendar and make sure every event is public and has the right information: This will include contacting hosts, confirming their participation, and making sure links are properly set.
* Assist all community calls and answer any question the host can't on behalf of govNerds (making sure to state we are not part of OP Fnd team).
* Announce on corresponding channels Delegate activities, Citizen activities, OP find workshops, and any sort of event delegates /citizens should be aware of.
* Check every mission proposal, keep track of delegate approvals, verify the delegate has the correct % needed to approve a project, and highlight passed-to-vote proposals to the foundation.
* Check the forum tools and make sure the spam filter is working properly and not blocking a mission proposer because of the many links posted. 

Once every cycle:
* Publish a roundup in the forum of passed missions moving to Agora
* Publish a roundup in the forum of voted proposals.
* Complete the [Optimism GovFund Grants: Public Distribution Tracking](https://docs.google.com/spreadsheets/d/1Ul8iMTsOFUKUmqz6MK0zpgt8Ki8tFtoWKGlwXj-Op34/edit?usp=sharing)

**Please verify that you are able to commit up to 8 hours per week to this role:** Yes I can commit 8 hs per week

**Grants are awarded in OP, locked for one year. Please acknowledge that you are aware of the grant policies [link]:** Yes

Please list any additional support you would require to execute this mission (financial, technical, etc.):
* 5000 OP locked for 1 year
* Discord moderator access to be able to tag delegates, citizens, etc
* Forum moderator access to manage spam filter approvals and forum open/close posts if needed.
* 15-30 minuted weekly meeting with 1 OP Fnd representative to verify their needs are being covered and check scope.

**Comment by Netrim** [comment]
**Applicant:** Netrim
**Contact info:** notnetrim@gmail.com
**L2 recipient address:** 0x5920ca4a51d93052f111e90c387f70bcf723ea3f
**Please verify that you meet the qualifications for submitting at the above:** I am Ember Tier 
**Please acknowledge that you will need to complete a KYC process to receive this grant:** Yes
**Please link to any relevant previous work:** Part of the Working Group for Seed LATAM behind the Joxes.eth delegation since Optimism Governance launched, including working on the DeFi and Tooling Committees from Season 2 as part of said delegation

**What makes you best-suited to execute this Mission? Please consider any experience relevant to the above requirements:**
I have been an active participant on the Optimism Governance process since the very beginning, guiding proposers within the different (and changing) templates back when the collective was still cementing an identity, as well as part of other DAOs on a personal or professional capacity.


**Please explain your familiarity with Optimism Governance and the proposal process:**
I have been an active participant in the forum since the Phase1 discussion, driven by the original Phase0 batched approval. I am also part of the Working Group for Seed LATAM which has remained active thru the different iterations the Optimism Collective has endured.  I decided early on that I didn't want to be delegate and preferred to have my participation be indirect by way of the SEED LATAM collective.

**Please describe the impact you aim to make in completing this Mission:**
The Reflection Period should be a moment to take stock, refill energy and be prepared for the next cycle. Nevertheless its also a great downtime period to increase the information flow that happens between the Foundation, delegates, badge holders and general interested parties.


**Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833)] that should be used to determine whether you’ve executed on this proposal. Make sure you understand what a critical milestone is before answering this question:**

Reflection Period Engagement:

- Maintain and secure the shared calendar for governance milestones
- Attend all community calls, answering questions as needed on behalf of the govNERDS initiative.

Proposal Feedback Process:

- Collaborate with the Optimism Foundation to create a comprehensive guide for proposers on using proposal templates effectively, and actively encourage their adoption during the Reflection Period.

Proposal Approval Process:

- Establish a clear communication channel to promptly share proposals that require delegate approval, ensuring they are reviewed well in advance of the voting deadline.

Proposal Voting Process:

- Send regular reminders to delegates about Special Voting Cycle start and end dates, as well as other key deadlines during the Reflection Period, to maximize participation and engagement.

Forum Management:

- Identify and address low-quality forum engagement, including spam or irrelevant posts, to maintain a constructive discussion environment during the Reflection Period, including drawing the attention of the Optimism Foundation as needed.

**Please verify that you are able to commit up to 8 hours per week to this role:** Yes

**Grants are awarded in OP, locked for one year. Please acknowledge that you are aware of the grant policies [link]:** Yes

Please list any additional support you would require to execute this mission (financial, technical, etc.):

5000 OP locked for 1 year
Discord role with access to tag specific roles like delegates, citizens, nerds. Ideally Discord role should contain timeout functions and kick/ban privileges, as well as manage messages for the required channels.
Discourse function above "Licensed" which should allow me to moderate (close/open, timeout members, review spam) as needed.
Up to 30 minutes on a weekly touch base with an Optimism Foundation representative for this RFP to validate scope, raise awareness and/or draw attention to topics as needed

**Comment by wethedante** [comment]
- **Applicant:** Dante
- **Contact info:** we.the.dante@gmail.com
- **L2 recipient address:** 0x968ec3ebf1cd3ab68067c04e84ab7eb5fdbab153
- **Please verify that you meet the qualifications for submitting at the above [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877):** I am Ember Tier 
- **Please acknowledge that you will need to complete a KYC process to receive this grant:** ✅
- **Please link to any relevant previous work:** 
    * [JetDAO's Asset Onboarding Framework](https://forum.jetprotocol.io/t/introducing-jet-protocol-s-asset-onboarding-framework/830)
    * [JetDAO's Updated Collateral Onboarding Domain Evaluation Criteria (CODEC)](https://forum.jetprotocol.io/t/new-codec-guiding-jet-set-offs/912)
    * [Addressing Voter Apathy](https://forum.jetprotocol.io/t/addressing-voter-apathy/1341)

**What makes you best suited to execute this Mission? Please consider any experience relevant to the above requirements:** 

Governance Accessibility Experience 
- As the Governance Lead at JetDAO, I was the liaison between the founding team of Jet Protocol, Token holders, asset applicants, and community members. 
- I was responsible for drafting and implementing the Asset Onboarding Framework, a governance structure that created a clear and accessible path for anyone to engage meaningfully with JetDAO's Governance Process. 
- I advocated for both on-chain and off-chain consensus methods, clear and defined review processes, and community feedback methods that lowered the barrier to governance participation and understanding. 

Tooling Experience 
- I introduced the JetDAO Community Public calendar, which communicated voting cycles, deadlines, and community calls. 
- I supported community call logistics, content curation, [JetDAO.fi/news](https://www.jetdao.fi/news) updates, and I welcomed experimenting with additional tools and platforms to increase voter participation. 
- I fought on the front lines against spam in Discord and Discourse and was trusted with delegating critical matters to the core team. 

Personal Drive
- My work experience closely aligns with the mission's requirements.
- My enthusiasm for understanding the impact of public goods on governance fuels my dedication to contributing to the community.

**Please explain your familiarity with Optimism Governance and the proposal process:**

- As an Ember Tier trust contributor, I have an outsider's understanding of OP's Governance process. However, as a DAO native and Governance Designer, I am very familiar with the intentions and purposes of the processes. 
- The Token House follows a 'traditional' DAO consensus method, with permissionless tokenholders and delegates voting on the decision. 
- The Citizen's House uses a 'one-person, one-vote' consensus method, aligning the values of human stakeholders with long-term goals. 
- The proposal process for the Token House is well-defined and documented, with consistent cycles, deadlines, and platforms for engagement. 

**Please describe the impact you aim to make in completing this Mission:**

My Impact Objectives:
- Engage actively with delegates during the Reflection Period.
- Foster an efficient forum environment for meaningful discussions.
- Deliver governance accountability and legitimacy by lowering the barriers of participation and onboarding debt.
- Operate administrative tasks such as maintaining the public governance calendar and independently handling questions related to procedures.
- Ensure proposal quality and enhance community contributions by guiding members to collaboration and constructive consensus. 
- Build stronger bonds between the governance system, its participants, and the broader DAO community. 


**Please define the [critical milestone(s)](https://gov.optimism.io/t/collective-grant-policies/5833#critical-milestones-and-clawback-6) that should be used to determine whether you’ve executed on this proposal:**

Passive Critical Milestones:
- Posts on the Forum and in Discord within 48 hours that provide delegates with a relevant understanding of the proposal process, reflection period, and documentation. 
- Completing updates on the Public governance calendar within 48 hours of the need arising. 
- "<3-ing" all Reflection Period proposals reviewed, and commenting where proposals are non-compliant within 48 hours. 
- Forum Post history will show proposals where tags and pins were managed for increased visibility. 

Active Critical Milestones: 
- Attendance and active participation in all delegate community calls, with a written summary published after the call. 
- Post in the Forum and Discord 24 hours before the start and end of the Special Voting Cycle and any other critical deadlines, alerting delegates of the deadline and proposal requiring their review. 
- Author and post-voting cycle Roundups, adding approved proposals to the roundup before the deadline. 


**Please verify that you are able to commit up to 8 hours per week to this role:**
- Yes, I commit to dedicating 8 hours per week to this role.


**Grants are awarded in OP, locked for one year. Please acknowledge that you are aware of the [grant policies](https://gov.optimism.io/t/collective-grant-policies/5833)**: 
- Yes, I'm familiar with the grant policies.


**Please list any additional support you would require to execute this mission (financial, technical, etc.):**
- 3,000 OP locked for 1 year (Baseline Grant)
- Discourse permissions to moderate topics and posts for shaping discussions on proposals. 
- Discord permissions to moderate spam and tag proper parties for voting cycles. 
- Google Calendar permissions for public calendar management. 
- 30-minute onboarding meeting with OP Foundation liaison.

**Comment by brichis** [comment]
Applicant: Brichis
Contact info: 
E-mail: briciaguzman@gmail.com 
Telegram / Discord: @brichis
L2 recipient address: brichis.eth
Please verify that you meet the qualifications for submitting at the above [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877): Yes, I do
Please acknowledge that you will need to complete a KYC process to receive this grant: Yes, I have no problem completing KYC
Please link to any relevant previous work: 
[Delegate](https://gov.optimism.io/t/brichis-delegate-communication-thread/6353)
Co-Founder of [Ethereum México](https://twitter.com/Ethereum_Mexico)
[POAP Gallery](https://app.poap.xyz/scan/brichis.eth)
[Session on Optimism Governance for Beginners in Spanish](https://vine-elf-e5c.notion.site/Sesi-n-2-Gobernanza-caae546b566d4672904d88b9a089ba20)

What makes you best-suited to execute this Mission? Please consider any experience relevant to the above requirements:
1. Active Delegate Engagement: I've been an active delegate since earlier this year, actively participating in forum discussions and engaging in governance conversations on Discord. This experience has allowed me to deeply understand Optimism's mission and its governance intricacies.

2. Community Management Expertise: My background as a community manager and community builder has equipped me with valuable skills in communication, engagement, and relationship-building. These skills are essential in effectively shepherding proposals and fostering positive interactions within the community.

3. Efficiency and Organizational Skills: My bachelor's degree in accounting has honed my ability to be efficient, organized, and systematic in my approach. These qualities are crucial when managing administrative tasks related to the proposal process and maintaining governance calendars.

4. Customer Service Experience: My previous experience in the restaurant business has cultivated strong customer service skills. I understand the importance of being approachable and responsive, which translates well into creating a positive and supportive environment within the governance community.

Please explain your familiarity with Optimism Governance and the proposal process:
I jumped into the role of a delegate after RetroPGF 2, which was a game-changer for Ethereum México thanks to the funding we secured. That experience sparked a newfound passion within me as I delved into the inspiring world of Optimism Vision. Over this period, I've been on a constant learning journey, soaking up knowledge from some of the most active and dedicated participants in the Optimism community. It would be an absolute honor to collaborate and work side by side with this incredible group.

Please describe the impact you aim to make in completing this Mission:
By taking on the role of a govNERD, I intend to streamline the governance process, making it more accessible and efficient for everyone involved.

I want to ensure that high-quality proposals receive the attention and feedback they deserve, helping the community identify and nurture innovative ideas. I aim to create a collaborative environment where proposers, delegates, and community members can work together seamlessly, ultimately leading to better decision-making and a more vibrant Optimism ecosystem.

Additionally, I hope to contribute to reducing the administrative burden on the Optimism Foundation, allowing them to focus on strategic initiatives. By actively managing forum engagement, tags, and forum spam, I aim to create a cleaner and more organized space for meaningful discussions.

Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833) that should be used to determine whether you’ve executed on this proposal. Make sure you understand what a critical milestone is before answering this question:
1. Reduction in Foundation Involvement. At the end of the period, the people in charge of governance at the foundation will have to spend fewer hours on tasks such as maintaining the governance calendar, addressing procedural queries, and making announcements to delegates.
2. Increased Delegate Participation. Increase the % of participation among the top 100 delegates during the Reflection Period.
3. Reduction in Forum Spam. A decrease in spam reports would demonstrate that the forum environment has improved.

Please verify that you are able to commit up to 8 hours per week to this role: Yes, I am

Grants are awarded in OP, locked for one year. Please acknowledge that you are aware of the grant policies [link]

[...]
Please list any additional support you would require to execute this mission (financial, technical, etc.):

I'm fully committed to executing this mission effectively. However, as a mother, I do have some financial considerations. Monthly income is crucial for me, and waiting for a year to receive funds isn't feasible. To align better with my financial needs, I would appreciate the opportunity to receive the proposed 3,000 OP in two payments, one in October and the other in November.

In addition to financial support, here are some other forms of assistance that would greatly aid in executing this mission:
- Discord Admin Permissions
- Forum Permissions
- Direct Communication: Establishing direct communication with someone from the foundation and fellow govNERDs would facilitate seamless collaboration and swift decision-making.
- Introduction to govNERDs Program: A comprehensive introduction to the govNERDs program would help me fully understand the program's goals, processes, and how I can contribute most effectively.

**Comment by honn24xx** [comment]
**Applicant**: Honn
**Contact info**: honnkay24@gmail.com
**L2 recipient address**: 0xa19abba88C70F02d8D5E4B10f5979709b3F37fb5
**Please verify that you meet the qualifications for submitting at the above [[Tier](https://gov.optimism.io/t/collective-trust-tiers/5877)](https://gov.optimism.io/t/collective-trust-tiers/5877):** I am Ember Tier.
**Please acknowledge that you will need to complete a KYC process to receive this grant:** Yes
**Please link to any relevant previous work:** Link [DAO treasury report](https://daocollective.xyz/treasury-management/), [led first DAO delegate race](https://gov.uniswap.org/t/launch-of-uniswap-agora-delegate-race/21133), [Uniswap governance reform](https://www.coindesk.com/web3/2022/12/21/uniswap-dao-community-members-vote-in-favor-of-new-governance-process/), started [Optimism protocol delegation program for Uniswap](https://gov.uniswap.org/t/uniswap-optimism-protocol-delegation-committee-update/20812), led [Optimism liquidity mining for Uniswap] (https://gov.uniswap.org/t/phase-3-optimism-uniswap-protocol-liquidity-mining-program-update/21068).

**What makes you best-suited to execute this Mission? Please consider any experience relevant to the above requirements:**
- **DAO governance leadership & expertise:** I previously helped lead governance and grants for Uniswap as one of the founding employees of the Uniswap Foundation. Prior to this, I worked as a grants evaluator for dYdX's grants program and also served as a governance lead for one of the largest student organization delegates in 2021. Outside of operating directly in DAOs, I was also a researcher for the DAO Research Collective, where I published a comprehensive report on DAO treasury management and served as a moderator for a DAO research summit at Stanford Blockchain Week in 2022. 
- **Operational excellence:** Prior to my experiences in crypto, I worked in management consulting at within MBB that gave me strong foundational operational skills. 

**Please explain your familiarity with Optimism Governance and the proposal process:**
- I am quite familiar with Optimism Governance and the proposal process through my involvement in the Optimism Protocol Delegation program. I led the efforts on the Uniswap end to actively serve as one of the largest protocol delegates in its inaugural cohort of protocols. In addition to this, I was constantly looking to leverage best practices for DAO processes, which was another way I continued to stay in the loop and keep up with Optimism governance. 

**Please describe the impact you aim to make in completing this Mission:**
- In completing this mission, I aim to help the Optimism community inch closer to its north star of a fully decentralized governance community. This will be done by helping take the load off of operational tasks for the Optimism Foundation's governance team, allowing them to spend more time on larger governance experiments and initiatives. Further, I aim to become someone that those participating in Optimism governance can rely on to simplify and clarify processes. 

**Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833)] that should be used to determine whether you’ve executed on this proposal. Make sure you understand what a critical milestone is before answering this question:**
**General governance process support:**
-  Actively communicate with delegates to ensure that they understand expectations and processes during Reflection Period. 
- Active communication will include attending all delegate community calls to clarify confusions and maintaining & updating the public governance calendar to reflect all relevant dates. 
- Alerting delegates for start and ends of Special Voting Cycles and other important deadlines during the Reflection Period so they know what needs their attention and votes. 
- Add approved proposals to the Voting Cycle Roundups before the deadline.

**Proposal feedback process monitoring:** 
- Monitor all proposals during the Reflection Period to follow templates, while listening for feedback and communicating that back to the Optimism Foundation. 
- Identify opportunities for collaboration by looking for overlap in proposals, while reducing unnecessary proposals. 
- Actively reach out to delegates on important proposals to ensure that the proposal is on their radar for feedback. 

**Forum Management:**
- Assist in reducing low quality forum content, while aiding the discoverability of relevant proposals through discourse tags.

**Please verify that you are able to commit up to 8 hours per week to this role:** Yes, I am able to commit up to 8 hours per week for this role.

**Grants are awarded in OP, locked for one year. Please acknowledge that you are aware of the grant policies:** Yes, I am aware. 

**Please list any additional support you would require to execute this mission (financial, technical, etc.):**

- 3,000 OP locked for 1 year (Baseline Grant)
- Discord admin permissions
- Forum permissions
- Google calendar permissions
- Onboarding calls and weekly calls with member from Optimism Foundation to align expectations

**Comment by justine-hy** [comment]
Submissions for this Foundation Mission Request are now closed. Thanks to everyone who submitted a proposal!

Someone from the Optimism Foundation will reach out before September 21st to communicate which application(s) have been accepted and schedule a kickoff. We may also reach out individually using the contact info you've provided if we want to discuss your application in more detail.

**Comment by justine-hy** [comment]
Great to see all the applications for the first trial of govNERDs! 

We're excited to move forward with @Dhannte and @brichis! We'll be in touch shortly regarding an onboarding call before the start date. 

We were impressed by the quality of other applicants and would like to remind you this Mission Request is for an initial trial during the Reflection Period. If this experiment goes well, we may need more govNERDs to help in Season 5, and would encourage you all to re-apply then! 

cc @Nicca42

**Comment by oplavande** [comment]
Flagging #114 to all previous applicants!

**Comment by oplavande** [comment]
Summary of the initial govNERDs experiment! We will be continuing the govNERDs experiment in Season 5, adding an additional govNERD specifically to focus on Citizens' House. We hope to transition the govNERDs to an open contribution path for Season 6 and beyond. 

- @brichis and @Dhannte did an exceptional job (meeting the critical milestones that were in scope of this Mission Request) and were especially helpful in helping the Foundation: 

- Maintain the public governance calendar during the Reflection Period
- Answer governance questions in Discord and on community calls (@oplavande was able to spend less time answering procedural questions as a result) 
- Reduce the need for @oplavande to make announcements pertaining to voting cycles or general governance schedules and to create Voting Roundups 
- Respond to forum feedback. The govNERDs were enormously helpful in raising issues on the forum an flagging feedback that warranted a response. The Foundation's forum response rate during the Reflection Period is almost entirely thanks to the govNERDs 

- While we had a very low response rate to the survey requesting delegate feedback about the govNERDs, delegates found the govNERDs most helpful in aiding with forum management, announcements in Discord, and clarity around Voting Cycles.  Feedback suggests the govNERDs could take on additional responsibilities, which is within scope for the Season 5 Mission Request. 

- We will calculate participation by Top 100 delegates in this Reflection Period vs. the last Reflection Period once complete; however, there are many other factors that may influence these rates and therefore we would not consider it a very accurate indicator as to the success of this experiment.

**Comment by Nicca42** [comment]
Hello everyone! 

We have picked our govNERDs for S5:
* @brichis 
* @Dhannte 
* @honn24xx 

We are super excited to have them with us for the upcoming season.

If you did not make the cut and still want to be a part of the team, don't worry! We will be keeping a close eye on community contributors this season and may even expand the group during the season if needed. So stay contributing! 

As always, 
Stay optimistic ✨

**Comment by opjulian** [comment]
Happy to announce that this Foundation Mission is back up for Season 6. Applicants have until May 3 May 3 23:59 GMT to apply! 

https://github.com/orgs/ethereum-optimism/projects/31/views/1?pane=issue&itemId=61133698
