### ISSUE TITLE
Foundation Mission Request: Proof of Attendance Testnet Faucet

### ISSUE THREAD

**Issue by bdresser** [ethereum-optimism/ecosystem-contributions#115]
## Foundation Mission Request – Proof of attendance testnet faucet 
_To take on this project, submit a proposal to this thread by December 8. Read more about Missions [here](https://gov.optimism.io/t/token-house-missions/5881)._

* **S5 Intent**: Grow the Superchain
* **Foundation Mission (RFP):** Build a way for hackathon participants to claim larger testnet funds from in person hackathons via the [Superchain Faucet](https://app.optimism.io/faucet)
* **Proposal Tier:**  [Ember](https://gov.optimism.io/t/collective-trust-tiers/5877) 
* **Baseline grant amount**: 30K OP
* **Accepting one or multiple proposals:** One 
* **OP Labs or Optimism Foundation Sponsor**: Zain (@zainbacchus)
* **Submit by**: December 8th at 19:00 GMT
* **Selection by**: December 15th at 19:00 GMT

### **How will this Foundation Mission (RFP) will help accomplish the above Intent?**

[Superchain Faucet](https://app.optimism.io/faucet) is a developer tool that allows developers to get free testnet ETH to test and build apps on testnet OP Chains like Base Sepolia, OP Sepolia, PGN Sepolia, Zora Sepolia, and other OP Chains in the Superchain. 

Developers who have an Optimist NFT, Gitcoin Passport attestation, or WorldID are able to get larger drips from the faucet. 

A common pain point for hackathon participants is not having credentials yet for larger drips. This RFP aims to expand access to larger testnet fund drips to participants at in person hackathons and reduce developer friction when building on OP Chains. 

As such, this mission will contribute to a more resilient developer ecosystem for the Superchain.

### **What is required to execute this Foundation Mission (RFP)?**

Completing this RFP requires building an open source frontend that allows users to claim a proof of attendance attestation, mint an Optimist NFT, and get larger testnet fund drips. The interface should be fully open-source and should allow for future iterations of the functionality. This RFP requires both designs and implementation.
, 
For this RFP, the Optimism Foundation will accept one submission.

The target grant reward for the submission will be 30K OP. Teams should discuss the solution criteria below with the Foundation, and may arrive at a different mutually agreeable grant amount dependent on the scope of their work.

### **Solution Criteria:**

Core functionality of the claim experience includes both a flow for event maintainers and an end user flow. 

**Proposed maintainer flow**
To set up the claim experience, the event maintainer should require minimal setup.
- Maintainer sets up a new event using an admin portal
- Maintainer is provided a URL to use for the specific in person events
- Maintainer sets up the URL at the respective event

**Proposed end user flow**
To claim the proof of attendance attestation the flow should be sybil-resistant, gasless, and allows the user to specify their preferred address. 
- Developers come to the OP booth 
- Developer scans the QR code or URL at the OP booth
- Developer completes challenge that proves they’re at the booth (eg by entering a unique code)
- Developer enters their wallet address or ENS name
- Developer gets a proof of attendance attestation and Optimist NFT minted to their specified address 
- Developer is prompted use the faucet to get larger drips from the faucet or customize their Optimist NFT

**Ethereum attestation service (EAS) and Optimist NFT**
[EAS](https://docs.optimism.io/identity/contracts-eas) is an open-source public good that is included as a predeploy in the OP Stack. The proof of attendance attestations should use the EAS contracts on OP Mainnet and requires a new schema for the proof of attendance attestations to be created. 

[The Optimist NFT](https://app.optimism.io/optimist-nft) is a fully customizable digital avatar that allows you to showcase your personality and build your onchain identity. 

Proposed implementation of proof of attestation / auto-minting the Optimist NFT:
- Create an [EAS resolver](https://docs.attest.sh/docs/tutorials/resolver-contracts) that restricts ability to create this attestation to specific addresses
- This resolver should maintain a mapping(address => bool) of everyone who currently has this attestation using the onAttest and onRevoke hooks
- Update [OptimistAllowlist](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/periphery/op-nft/OptimistAllowlist.sol).sol to check the resolver contract to see if user is eligible
- Auto-mint feature: Automatically mint the Optimist NFT to users who have the proof of attendance attestation
  - Option 1: The resolver should do the above, then directly mint the NFT
  - Option 2: Use multicall3 to 1. Create the attestation, 2. Use `function mint(address _recipient)` function on [OptimistNFT](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/periphery/op-nft/Optimist.sol) in a single transaction

### **How should the Foundation measure progress towards this Foundation Mission (RFP)?** 

Progress can be measured based upon the completion of the following milestones:

- Specification for implementation, design approach, and architecture for the functionality listed above.
- Open-source code repository to observe progress over time
- Launch of the interface

These milestones mark the completion of the proposal. 

## **How should RetroPGF badgeholders measure impact upon completion of this Foundation Mission (RFP)?**

- Number of attestations (by distinct addresses) that is triggered through this interface
- Number of contracts deployed on OP Chain testnets by addresses that have attestations from this interface

## Application instructions

_To apply for this RFP, please complete the form in the expandable section below and leave your response as a comment on this issue thread below. Submissions will be open until June 28, at which time the Foundation will review all submissions and select up to three individuals/teams to complete the work defined here._ 

<details>
  <summary>Submission form</summary>

_Copy the entire application below and leave a comment on this issue with your answers completed. A representative from the Optimism Foundation may reach out using the contact info provided to request more information as necessary._

## Foundation Mission (RFP) Application

**Please verify that you meet the qualifications for submitting at the above [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877/2)**

* **Alliance Lead:** Please specify the best point of contact for your team 
* **Contact info:** 
* **L2 recipient address:** 
* **Please list the members of your Alliance and link to any previous work:**

Read more about Alliances [here](https://gov.optimism.io/t/season-4-alliance-guide/5873)

--- 

**What makes your Alliance best-suited to execute this Mission?**
- [...]
- [...]

**Please describe your proposed solution based on the above Solution Criteria (if applicable):**
- [...]
- [...]

**Please outline your step-by-step plan to execute this Mission, including expected deadlines to complete each peice of work:**
- [...]
- [...]

**Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833) that should be used to determine whether you’ve executed on this proposal:** 
- [...]
- [...]

**Please list any additional support your team would require to execute this mission (financial, technical, etc.):** 
- [...]
- [...]

**Grants are awarded in OP, locked for one year. Please let us know if access to upfront capital is a barrier to completing your Mission and you would like to be considered for a small upfront cash grant:** _(Note: there is no guarantee that approved Missions will receive up-front cash grants.)_
- [...]

Please check the following to make sure you understand the terms of the Optimism Foundation RFP program:

- [ ] I understand my grant for completing this RFP will be locked for one year from the date of proposal acceptance.
- [ ] I understand that I will be required to provide additional KYC information to the Optimism Foundation to receive this grant
- [ ] I understand my locked grant may be clawed back for failure to execute on critical milestones, as outlined in the [Operating Manual](https://github.com/ethereum-optimism/OPerating-manual/blob/main/manual.md#valid-proposal-types)
- [ ] I confirm that I have read and understand the [grant policies](https://gov.optimism.io/t/token-house-grant-policies/5833)
- [ ] I understand that I will be expected to following the public grant reporting requirements outlined [here](https://gov.optimism.io/t/suggested-public-reporting-requirements-for-grantees/4176)

-- end of application --

---

</details>

**Comment by zainbacchus** [comment]
Love that feedback @0xyNaMu 

> want to use your main wallet to deploy a smart contract to tesnet or even to connect it to anything you're building at a hackathon 

This is actually why we didn't specify mainnet deployments as we don't expect the hackathon participant to use the same keypair across mainnet and testnet deployments. 

Interesting call out on testnet - rather than replacing the specified measurement what do you think about adding a third measurement:

`Number of contracts deployed on OP Chain testnets by addresses that were funded from addresses that have attestations from this interface`

That way we can learn which is a better proxy towards our goal of getting more developers building on Optimism blockspace.

**Comment by cdpiano** [comment]
<h1>Foundation Mission (RFP) Application</h1>
<p><strong>Alliance Lead</strong>: Yuchen Jiang</p>
<p><strong>Contact info</strong>: yuchen@jomo.network</p>
<p><strong>L2 recipient address</strong>: 0x56EA5d2d923a44E5d7F974FDa9CAB06A6Ae40eC4</p>
<p><strong>Team members</strong>: Yuchen Jiang, Charlie Chen, Kevin Yin</p>
<p><strong>Past work:</strong></p>
<p>We’re the team behind <a href="https://jomo.id/">Jomo</a>. We aim to empower on-chain experience with off-chain data.</p>
<p><strong>A few other things we built:</strong></p>
<ul>
<li><strong>RealReturn</strong> - an open leaderboard of verified real investment returns, enabled by TLSNotary and Jomo.
<ul>
<li><a href="https://ethglobal.com/showcase/realreturn-pu64y">https://ethglobal.com/showcase/realreturn-pu64y</a></li>
</ul>
</li>
<li><strong>CryptoWharf</strong> - Democratizing Early Stage Startup Fundraising and Investing on Web3
<ul>
<li><a href="https://ethglobal.com/showcase/cryptowharf-c4sjx">https://ethglobal.com/showcase/cryptowharf-c4sjx</a></li>
</ul>
</li>
</ul>
<h2>What makes your Alliance best-suited to execute this Mission?</h2>
<p>We're the team behind Jomo, a project aimed at enhancing on-chain experiences with off-chain data. Supporting developers in the Optimism hackathon by helping them mint attestations and claim larger faucet drips aligns closely with our vision.</p>
<p>Our prior work at Jomo involves building attestations for off-chain data, such as minting an attestation to prove the receipt of an email from a community. This domain expertise gives us an advantage in implementing this RFP.</p>
<p>We have actively participated in hackathons, winning finalists at the ETHNewYork hackathon <a href="https://ethglobal.com/showcase/realreturn-pu64y">(link)</a>. Implementing this RFP addresses our own needs, which further gets us excited!</p>
<h2>Please describe your proposed solution based on the above Solution Criteria (if applicable):</h2>
<h3><strong>Organizer admin tool</strong></h3>
<ul>
<li>Enable the organizer to input hackathon metadata, such as the title, description, and logo.</li>
<li>Allow the organizer to enter the expected number of participants (for example, if 150 developers are anticipated to attend the event, the goal would be to provide attestation for them).</li>
<li>The website should generate a list of unique QR codes equivalent to the number of expected participants entered by the organizer. (Developers can only mint attestation after scanning the code, and each code can be used only once).</li>
<li>Allow the organizer to invalidate unused codes after a hackathon ends.</li>
</ul>
<p>Please note, we anticipate that the organizer will print the QR codes on flyers and distribute them at the hackathon. The design and printing of these flyers are not within the scope of this RFP.</p>
<h3>Mint attestation page</h3>
<ul>
<li>A secure attestation mint page that can only be accessed with valid URLs (e.g., use a code in the URL parameter to validate the link).</li>
<li>A section to provide the context of the mint (e.g., explaining what the attestation is and its uses).</li>
<li>A dialog box for developers to enter their wallet address or ENS name.</li>
<li>Proof of attendance attestation and Optimist NFT are minted once the developer enters their wallet. Gas fees are covered. See next section for details.</li>
<li>A page to guide developers on the possible use cases for the attestation/NFT, e.g. using the faucet to get larger drips or customizing their Optimist NFT.</li>
</ul>
<h3>EAS and Optimist NFT</h3>
<ul>
<li>Create a new schema (optimist.hackathon-participants) for the proof of attendance attestations using EAS contracts on the OP mainnet.</li>
<li>Issue the attestation to developers who enter wallets by scanning the QR code.</li>
<li>Update <a href="https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/periphery/op-nft/OptimistAllowlist.sol">OptimistAllowlist</a> to verify the optimist.hackathon-participants attestation to determine user eligibility.</li>
<li>Use the mint function on <a href="https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/periphery/op-nft/Optimist.sol">OptimistNFT</a> to automatically mint the Optimist NFT for the developer.</li>
</ul>
<h3><strong>Appendix: End user flow during hackathon</strong></h3>
<ul>
<li>Developers come to the OP booth</li>
<li>Developer picks a flyer and scans the QR code</li>
<li>Developer enters wallet address or ENS name</li>
<li>Developer gets a proof of attendance attestation and Optimist NFT minted to their address</li>
<li>Developer is prompted use the faucet to get larger drips from the faucet</li>
</ul>
<h2>Please outline your step-by-step plan to execute this Mission, including expected deadlines to complete each piece of work:</h2>
<ol>
<li>Design the UI and UX for both the organizer and user flow.</li>
<li>Implement the organizer admin tool:
<ul>
<li>Input hackathon metadata</li>
<li>Generate unique QR codes</li>
<li>Create flyers ready for printing</li>
</ul>
</li>
<li>Implement the mint attestation frontend:
<ul>
<li>Secure permissioned URLs</li>
<li>Develop frontend UI before mint</li>
<li>Develop frontend UI after mint</li>
</ul>
</li>
<li>Create attestation and Optimist NFT:
<ul>
<li>Interact with EAS to create an attestation</li>
<li>Update the smart contract to include the auto mint feature</li>
</ul>
</li>
<li>Testing &amp; QA:
<ul>
<li>Collaborate with the Optimism team for testing</li>
<li>Launch live during an Optimism hackathon at the end of February</li>
</ul>
</li>
</ol>

Milestone | Done by
-- | --
Design | 2024-1-15
organizer admin tool | 2024-1-25
Mint attestation frontend | 2024-2-5
Create attestation and NFT | 2024-2-15
Testing & QA | 2024-2-29


<p><strong>Please define the <a href="https://gov.optimism.io/t/grant-policies/5833">critical milestone(s)</a> that should be used to determine whether you’ve executed on this proposal:</strong></p>
<p>We will complete the product design by January 15.</p>
<p>We will finish all engineering work by February 15.</p>
<p>We will have the product in production and conduct live tests with OP by February 29.</p>
<p><strong>Please list any additional support your team would require to execute this mission (financial, technical, etc.):</strong></p>
<p>Conduct ad-hoc check-ins for demos and to get feedback.</p>
<p><strong>Grants are awarded in OP, locked for one year. Please let us know if access to upfront capital is a barrier to completing your Mission and you would like to be considered for a small upfront cash grant: (Note: there is no guarantee that approved Missions will receive up-front cash grants.)</strong>
We do not need upfront capital to do this.</p>
<p>Please check the following to make sure you understand the terms of the Optimism Foundation RFP program:</p>

[x] I understand my grant for completing this RFP will be locked for one year from the date of proposal acceptance.

[x] I understand that I will be required to provide additional KYC information to the Optimism Foundation to receive this grant

[x] I understand my locked grant may be clawed back for failure to execute on critical milestones, as outlined in the <a href="https://github.com/ethereum-optimism/OPerating-manual/blob/main/manual.md#valid-proposal-types">Operating Manual</a>

[x] I confirm that I have read and understand the <a href="https://gov.optimism.io/t/token-house-grant-policies/5833">grant policies</a>

[x] I understand that I will be expected to following the public grant reporting requirements outlined <a href="https://gov.optimism.io/t/suggested-public-reporting-requirements-for-grantees/4176">here</a>
<p>-- end of application --</p>

**Comment by mendesfabio** [comment]
## Foundation Mission (RFP) Application

* **Alliance Lead:** Fábio
* **Contact info:** [fabio@bleu.studio](mailto:fabio@bleu.studio) | mendesfabio (Discord)
* **L2 recipient address:** `0xa41214012d4462ecBB0724673897Ee0dCc0fDF49`

**Alliance Members**

- @mendesfabio
- @ribeirojose
- @yvesfracari
- @luizakp
- @devjoaov

**Previous Work**

[bleu](https://github.com/bleu-fi) collaborates with companies and DAOs as a technology and user experience partner. Our goal is to help bridge the UX gap that exists for Web3 users. We've worked on several Balancer Grants and recently started contributing to the CoW Protocol.


- [Balancer] [Internal Balances Manager](https://balancer-tools.bleu.fi/internalmanager): manage tokens within Vault's Internal Balance. This dApp helped users affected by the Euler hack in recovering their funds when Euler eTokens were frozen;
- [CoW] [MilkmApp (WIP)](https://cow-tools-bleu-fi.vercel.app/) - Safe App for creating and managing Milkman orders which allows DAOs to sell tokens but deferring the choice of the price to the execution time (leveraging price checkers) instead of the order creation;
- [Balancer] [Pool Simulator](https://balancer-tools.bleu.fi/poolsimulator) - enhancing pool performance through data-driven simulations;
- [Balancer] [Historical APRs](https://balancer-tools.bleu.fi/apr) - explore pools' historical APRs coming from swap fee, BAL emissions, yield tokens, etc;
- [Balancer] [Pool Metadata](https://balancer-tools.bleu.fi/metadata) - streamlines on-chain pool metadata management via IPFS.

**What makes your Alliance best-suited to execute this Mission?**

* We've been looking for ways to start contributing to the OP ecosystem (have already applied for a RFP before) and this Ember Mission seems the perfect opportunity to kick off our collaboration. We understand the significance of growing the Superchain by reducing developer friction and facilitating access to testnet funds; 
* bleu is working closely to the most innovative DeFi protocols such as CoW Protocol and Balancer - read our announcements and applications at the [Balancer Medium](https://medium.com/@BalancerGrants/bleu-is-building-balancer-tooling-twitter-bots-simulators-and-much-more-545b579c46e0) and [CoW Forum](https://forum.cow.fi/t/grant-application-safe-app-for-creating-milkman-orders/1920);
* We pioneered several applications for Balancer - from dashboards and simulators to dApps. Having primarily focused on the web3 frontend in past projects, we are well-acquainted with the tech stack required for this mission;
* Our expertise in building intuitive frontends for blockchain applications positions us uniquely to execute this mission. Our past success in similar projects serves as a testament to our capability and commitment.


**Please describe your proposed solution based on the above Solution Criteria (if applicable):**

### Frontend (Admin & Minting)

As requested, we're creating 2 separate pages/tools for Admin and Participants. 

- The Admin Portal will enable maintainers to create and managed events via seamless interfaces. Admins will have to fill a form with information regarding event (name, description, location, etc) but that can be edited later on via the Management page. Events must have start and end dates so URLs and QR codes expire after that period - if maintainers want to finish it early that should be possible with the Management features;
- The Participant Interface allows users to prove they’re at the event, claim a proof of attendance attestation and mint an Optimist NFT to any given wallet address (ENS supported). We're thinking of linking the Success page to relevant Developer docs of the OP ecosystem.

Our tech stack is chosen for reliability, documentation quality, developer experience, and community support. It includes:

- **Frontend**: Next.js, Tailwind.css, React Query, viem/wagmi, and React Hook Form;
- **Backend**: Prisma/Drizzle with Postgres/MySQL (if needed), and Vercel for deployment.

### EAS & NFT Integration

We're following the proposed solution for the proof of attestation / auto-minting NFT. An EAS Resolver will be created for tracking everyone who has the attestation. `multicall3` will be used for creating attestation and minting the NFT in a single transaction.

**Please outline your step-by-step plan to execute this Mission, including expected deadlines to complete each peice of work:**

1. **Specifications (1 week)**
   - User flows and UI designs;
   - Project setup.
2. **Admin/Maintainer Portal (2 weeks)**
   - Event creation and management tools:
        - Create an event;
        - Manage the current events;
        - Generate unique URLs and QR Codes;
        - Export QR Code - to be added to flyers.
3. **Mint Attestation & NFT Frontend (2 weeks)**
   - User interface development for attestation and NFT minting:
        - Initial/Challenge page (where user inputs code);
        - Minting Attestation & NFT UI implementation;
        - Minting Success/Failure UI implementation.
4. **EAS & NFT Integration (2 weeks)**
   - Integrating EAS resolver and auto-mint functionality:
        - Create EAS resolver;
        - Update OptimistAllowlist;
        - Auto-mint with `multicall3`.
5. **Testing & QA (1 week)**
   - Extensive testing and final deployment preparations:
        - Extensive testing and bug fixes;
        - Deployment to production.


| Milestone                        | Deadline         |
|----------------------------------|------------------|
| Specifications                   | December 28, 2023|
| Admin/Maintainer Portal          | January 12, 2024 |
| Mint Attestation & NFT Frontend  | January 26, 2024 |
| EAS & NFT Integration            | February 9, 2024 |
| Testing & QA                     | February 16, 2024|

\* Assumes a starting date of Dec 18th 2023 and considers expected OOOs for EOY holidays.

**Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833) that should be used to determine whether you’ve executed on this proposal:**


- Creation of an open-source repository and deployment preview: **January 4, 2024.**
- Functional deployment of Admin/Maintainer Portal: **January 12, 2024.**
- Deployment of Minting Frontend: **February 6, 2024.**
- Production deployment for community feedback: **February 16, 2024.**


**Please list any additional support your team would require to execute this mission (financial, technical, etc.):**

* Regular check-ins with the OP Team;
* Constructive feedback from the OP Sponsor and Team - bleu is committed to share bi-weekly written updates and Looms videos showing the progress.

**Grants are awarded in OP, locked for one year. Please let us know if access to upfront capital is a barrier to completing your Mission and you would like to be considered for a small upfront cash grant:** _(Note: there is no guarantee that approved Missions will receive up-front cash grants.)_

* Access to upfront capital is not a barrier; however, we do appreciate being considered for it. We understand it's not guaranteed.

Please check the following to make sure you understand the terms of the Optimism Foundation RFP program:

* [x]  I understand my grant for completing this RFP will be locked for one year from the date of proposal acceptance.
* [x]  I understand that I will be required to provide additional KYC information to the Optimism Foundation to receive this grant
* [x]  I understand my locked grant may be clawed back for failure to execute on critical milestones, as outlined in the [Operating Manual](https://github.com/ethereum-optimism/OPerating-manual/blob/main/manual.md#valid-proposal-types)
* [x]  I confirm that I have read and understand the [grant policies](https://gov.optimism.io/t/token-house-grant-policies/5833)
* [x]  I understand that I will be expected to following the public grant reporting requirements outlined [here](https://gov.optimism.io/t/suggested-public-reporting-requirements-for-grantees/4176)

**Comment by ryan-foamspace** [comment]
Foundation Mission (RFP) Application

Please verify that you meet the qualifications for submitting at the above [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877/2)

- Alliance Lead: Ryan King
- Contact info: ryan@foam.space
- L2 recipient address: foamspace.eth 
- Please list the members of your Alliance: [Kristoffer Josefsson](https://github.com/kejace), [Ilya Ostrovskiy](https://github.com/iostat)


- Previous work:

[FOAM](https://foam.space/) is building a Proof of Location protocol for onchain location proofs. We have shared work on our [MVP of smart contracts](https://mirror.xyz/foamspace.eth/DY8gLy7PBOQYMwkd6tEn6AdVEVV_9e7mldghX1Igkdg) and frontend being built on the OP Stack. We have many years of experience building frontend and backend systems, as well as writing firmware and integrating hardware into Ethereum smart contracts and user flows. 

Additional previous work that is relevant for this application is:

- The [FOAM Map](https://map.foam.space/) is a a dApp running on Ethereum 
 - [The FOAM Lite gateway ](https://f-o-a-m.github.io/foam.developer/foamlite/approach.html)and user transmitter, a part of this application, was built, documented and distributed at ETH Denver 2022. 
  - [CryptoKitty Monitor,](https://github.com/f-o-a-m/purescript-kitty-monitor) a frontend for viewing NFTs as they are minted 
 - [Kepler](https://github.com/f-o-a-m/kepler) a Haskell Implementation of the Cosmos SDK 


----------

What makes your Alliance best-suited to execute this Mission?

- Our Alliance is best- suited to execute this Mission because we are already working on Proof of Location and have many pieces already developed to fulfill this RFP for a Proof of Attendance Testnet Faucet . 


    For example, through our work with the OP Stack and running a custom rollup we have experience developing faucet flows for various OP testnets that include a user pairing their keypair to a mobile radio transmitter. Additionally, a subset of the Proof of Location protocol called FOAM Lite can already support gasless attestations and the minting of NFTs.


Please describe your proposed solution based on the above Solution Criteria (if applicable):

- Our proposed solution is to change the user flow and remove the scanning of QR codes with smart phones. In its place we propose utilizing a FOAM Lite gateway and mobile transmitters for end users. This increases sybil-resistantance and builds a more robust way of verifying attendance. 


    The FOAM Lite gateway is a built with the LoRa radio, a long range and low power internet of things device. FOAM Lite has firmware for it to serve as an Ethereum relayer and can decode and recover Ethereum signatures over the air from mobile transmitters and relay the necessary information onchain. 


    In our proposed solution a single FOAM Lite gateway will be set up at the OP booth for each event. Additionally, Optimism branded mobile transmitters will be made available at each event for developers that require larger drips from the faucet, supported by this grant. 


    Developers will then be able to link their mobile transmitter to their Ethereum address by completing a challenge protocol. Developers will then be able to send a signed transaction over the air that can be received, decoded and relayed onchain by the FOAM Lite gateway. From here developer get a proof of attendance attestation and Optimist NFT minted to their specified address and will be directed to the faucet. 


    Further, our proposed solution includes a open source frontend for both developers to go through this user flow as well as an Admin portal for setting up this user flow for each event and analytics that can display the number of attestations (by distinct addresses) that are triggered through this interface. 

Please outline your step-by-step plan to execute this Mission, including expected deadlines to complete each peice of work:


- Step 1: Create an EAS Resolver and smart contracts that are dependent on integrations with the FOAM Lite relayer that will relay incoming attestations from developers mobile transmitters.  FOAM Lite will maintain a mapping of all attestations relayed onchain to the resolver, update [OptimistAllowlist](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/periphery/op-nft/OptimistAllowlist.sol).sol and auto mint the [OptimistNFT](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/periphery/op-nft/Optimist.sol) . (1 week)
- Step 2: Modify existing user frontend flow and challenge for pairing and ingesting a mobile nodes signature to their desired Ethereum address and prepare this frontend to be part of the 
    open source frontend for the RFP. (1 week). 
- Step 3: Implement Admin organizer front end page for each hackathon and Admin user flow for setting up the FOAM Lite gateway to the EAS Resolver. (2 weeks)
- Step 4: Implement Developer facing frontend for seeing their attestations and NFTs as well as integration with the different testnet faucets. (1 weeks) 
- Step 5: QA testing and implementing feedback (1 week)


Please define the [critical milestone(s)](https://gov.optimism.io/t/grant-policies/5833) that should be used to determine whether you’ve executed on this proposal:

- Critical Milestone 1: February 1st, 2024, core engineering work complete demonstrated by an open source repo of relevant code.
- Critical Milestone 2: February 15th, frontends and Admin portal complete and added to the open source repo. 

Please list any additional support your team would require to execute this mission (financial, technical, etc.):

- We would be interested in discussing additional support for producing mobile transmitters to be distributed to developers. 

Grants are awarded in OP, locked for one year. Please let us know if access to upfront capital is a barrier to completing your Mission and you would like to be considered for a small upfront cash grant: (Note: there is no guarantee that approved Missions will receive up-front cash grants.)

- We would be interested in discussing a cash grant as well as a reduced grant amount for capital that be used explicitly for producing mobile transmitters to be distributed to developers prior to the one year lockup.

Please check the following to make sure you understand the terms of the Optimism Foundation RFP program:

[ X]  I understand my grant for completing this RFP will be locked for one year from the date of proposal acceptance.
[ X]  I understand that I will be required to provide additional KYC information to the Optimism Foundation to receive this grant
[X ]  I understand my locked grant may be clawed back for failure to execute on critical milestones, as outlined in the [Operating Manual](https://github.com/ethereum-optimism/OPerating-manual/blob/main/manual.md#valid-proposal-types)
[ X]  I confirm that I have read and understand the [grant policies](https://gov.optimism.io/t/token-house-grant-policies/5833)
[ X]  I understand that I will be expected to following the public grant reporting requirements outlined [here](https://gov.optimism.io/t/suggested-public-reporting-requirements-for-grantees/4176)

**Comment by zainbacchus** [comment]
Thank you for your submission!! We'll review and revert with next steps! 

In the meantime, feel free to tag me here or reach out directly ([zain@opabs.co](mailto:zain@oplabs.co)) with any questions.

**Comment by zainbacchus** [comment]
Wow! There's some excellent proposals here! 

We're excited to share that we will be moving forward with the proposals from Jomo given their domain expertise building offchain attestation related products.

@cdpiano we will be in touch directly to kick off the project and discuss expectations in more detail.

For all other teams here: we'd love to help you find the right way to contribute to the Optimism Collective. See the rest of the issues in the Ecosystem Contributions repo for ideas, suggestions, and other possible projects. One that might be interesting is #117 

Thank you again for your proposals!

cc @mendesfabio , @justmert, @Cotabe , @ryan-foamspace

**Comment by chcharcharlie** [comment]
Status update (start - 20240320)

- Aligned on visual design: https://www.figma.com/file/ISOiQ8lfdJgJDCxviT5AKB/OP-Check-in?type=design&node-id=80-2876&mode=design&t=u1pZ7tbkCOtbg922-11
- Agreed upon product and engineering direction
- Opened PR https://github.com/ethereum-optimism/optimism/pull/9891 to edit OptimistAllowlist so the EAS Resolver can get user permission to mint OptimistNFT after the attestation.
- Tested flow from IRL checkin -> EAS attestation -> OptimistAllowlist -> OptimistNFT locally
- Forked OptimistAllowlist and OptimistNFT and tested on Testnet: https://sepolia.etherscan.io/tx/0x488316636ba5d3f7dd711288494e75fc37c9b3793571529d701c0ff2a40c5b17
- Frontend/Backend implementation in progress and preview ready very soon.

**Comment by zainbacchus** [comment]
Quick update - after syncing with the OpenLayer team (fka Jomo) we've aligned to remove the requirement to issue an Optimist NFT and use the [Superchain Faucet schema](https://docs.optimism.io/chain/identity/schemas#developer-schemas) as the authentication method for developers to get larger drips from the Superchain Faucet. 

The product should issue attestations using this [schema](https://optimism.easscan.org/schema/view/0x98ef220cd2f94de79fbc343ef982bfa8f5b315dec6a08f413680ecb7085624d7) with the following info:
    - additionalData: Should be your team’s name (eg OpenLayer - {event}, etc.)
    - Recipient: Public address of the user you’re issuing the attestation for
    - Expiration time: Set the expiration time to be 7-days after issuance

**Comment by zainbacchus** [comment]
UPDATE: At the moment, the Optimism Collective is no longer pursuing the completion of this RFP.

In the meantime, the Grants Council and Retro Funding rounds continue to be a sustainable resource for teams to receive grant funding for their contributions to the Optimism Collective. 

Again, we appreciate everyone's submissions and interest in this RFP! Please check out our other Mission Requests to see other ways your team can contribute to the Collective. Thank you, and stay optimistic!
