### ISSUE TITLE
🔴 Ecosystem Project Idea: Ecosystem Contributions Dashboard

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#12]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

You're on this GitHub repository, so you hopefully understand why this project board is valuable! We need YOUR help to make this project board even *more* valuable with a website that displays all of the open GitHub issues, highlights issues that are endorsed by certain community members, and helps users find the best way to contribute to the Optimism ecosystem.

## Possible Features

- Display active project ideas for people to work on.
- Let users search for project ideas by content, category, etc.
- Sort projects into different categories and tags.
- Give users a flow that helps them discover the perfect project or task to work on.

**Comment by JeanGuillemont** [comment]
I'll try to work on this one with charmverse bounties integration !

**Comment by InvitedTea** [comment]
I am working on this.

**Comment by JeanGuillemont** [comment]
Hi everyone ! 
I was again working on it since some update in Charmverse API and since i saw you have chosen Charmverse for your grant documentation. Providing this dashboard there seems quite natural given this decision.
[That's how it would look](https://app.charmverse.io/jeanguillemontspace/page-18968400364702487)

### Benefits of using this method 
- it can be easely replicated to optimism grant charmverse space (only need API key from charmverse team)
- All contribution related document in Charmverse
- it allows simple and quick improvements of the layout and the content
- it's synced everyday with this github (i would only need authorization to do request on graphql project so i can improve states)
- it allows bounties addition for contributions giving access to a grant
- sync process use n8n and will be opensourced so it can be forked and/or improved if necessary

### Remaining work (few days of work)
- content finetuning
- replicate to Optimism grant Charmverse space
- improve states to show when a task in ongoing or paused
- documentation for process opensourcing

If you see any other improvements, let's talk about it ! Otherwise i hope this contribution will help !

**Comment by shardulpilley** [comment]
Hey Folks, 

This is Shardul from Grant3.

We have an integration live for Optimism RFGs that gives a simple user journey for visitors to find and browse through contribution ideas list. Our platform syncs with the Github page of Optimism contributions list and displays it with additional data.  Please check out the advanced RFGs list here https://optimism.grant3.co/rfg

The team made some major design improvements so that OP collective aspirant contributors find it very intuitive and easy to find what they are looking for.



**Filter Contribution ideas based on various factors, by one click buttons**
- Category: Ecosystem Project, Draft Project, Mad Science, Foundation Mission, Contribution Opportunity
- Estimated Effort: XLarge, Large, Medium, Small
- Estimated Impact: XLarge, Large, Medium, Small
- Tags: OP Stack, Dev Tools, RetroPGF, Chain Infra, Consumer Apps, Governance, Gaming, Meta, Protocol, DeFi
- Search directly by contribution idea title

Additionally to view the source, the individual entries also provide a link to the original GitHub page

Any remaining work:
We present the final product, the team does not anticipate any additional major changes to the site layout. But if you want to make any more suggestions or need help with something, please feel free to reach out to the Grant3 team at sharp@grant3.co

Cheers

Some images of the site
![Contribution list](https://github.com/ethereum-optimism/ecosystem-contributions/assets/147347359/1753d113-ade1-4765-99d1-3e939549c503)
![Contributions landing page](https://github.com/ethereum-optimism/ecosystem-contributions/assets/147347359/6f41e151-c6cf-4a74-b813-4650385e720b)
![filters](https://github.com/ethereum-optimism/ecosystem-contributions/assets/147347359/4c759ee7-3d8d-47ad-b858-fe09b134e03e)
![Individual RFG detial page](https://github.com/ethereum-optimism/ecosystem-contributions/assets/147347359/93383f5e-bc1a-4117-9911-c7c15de2587a)

**Comment by Maxservais** [comment]
@smartcontracts I think this issue can be closed?
