### ISSUE TITLE
Delegate Mission Request: Superchain Accounts

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#136]
### Delegate Mission Request: Superchain Accounts: Accelerating meaningful participation in the Superchain Ecosystem.

**Delegate Mission Request Summary:**
To further enhance meaningful participation across OP Chains, we propose to develop Superchain Accounts, a Superchain native-smart accounts that leverage account abstraction features to enable OP chain users to earn Superchain Points for active on-chain participation, improve their Superchain Rank, and evolve their NFTs. Higher ranks would offer recognition and perks, such as access to Weekly Superchain Raffles and voting power in a snapshot strategy.

**S5 [Intent 3](https://gov.optimism.io/t/collective-intents-season-5/6883) Please list the Intent your Request aligns with here:** Intent 3 - Improve the Consumer Experience

**Proposing Delegate:** [OPMichael 5](https://vote.optimism.io/delegate/opmichael.eth).eth

**Proposal [Tier 1](https://gov.optimism.io/t/collective-trust-tiers/5877):** Ember Tier

**Baseline grant amount:** 40K OP

**Should this Foundation Mission be fulfilled by one or multiple applicants:** One

**Start date: February 2024

Completion date: June 30th, 2024**

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=645984b0-da09-435f-8953-a93dd88bf487)**

### Specification

Superchain Accounts are Superchain native-smart accounts that leverage account abstraction features that enable OP chain users to earn Superchain Points for active on-chain participation, improve their Superchain Rank, and evolve their NFTs.

The Superchain Accounts aim to serve as a user’s primary hub for Superchain activity, as it pulls together their progress across OP chains and rewards their participation. The solution should include an adopted, ideally modular, smart account standard that enables account creation and recovery, gas abstraction, and transaction bundling to allow for a seamless user experience for users. The solution should also enable on-chain data from at least three OP chains to be pulled into the Superchain Account and issue evolving Badges based on non-transferable Superchain Points that can be earned based on specified on-chain activity. Finally, the solution should include an evolving Superchain Rank that grants users access to additional perks. The mission includes an initial campaign period of at least 4 weeks, during which some OP incentives will be introduced to award active participation, which should be coordinated by the Mission recipient.

Account User Journey
As an OP Mainnet, Base, PGN user or other OP Chain user, I can create a Superchain Account on OP Mainnet and claim evolving badges and Superchain Points according to my on-chain account history on these networks. Claiming Badges and Superchain Points will be smooth and free due to the gas and signature abstraction functions enabled by Safe Protocol.

Based on my Superchain Points, I can increase my Superchain Rank, an evolving NFT that grants voting power in a snapshot strategy and the right to claim weekly raffle tickets in the Superchain Raffle.

Below is a lo-fi mock of how Superchain Accounts could look like; a detailed prototype should be produced at the end of the Design phase.

Superchain example
Superchain example
744×226 47.1 KB

**How will this Delegate Mission Request help accomplish the above Intent?**

Improving the Consumer Experience is all about creating utility. Adding more meaning to on-chain transactions increases their utility and, as a result, increases transaction volume and user retention.

Creating Smart Accounts that measure on-chain participation, incentivizes users to merge their potentially multiple EOA into one account (to increase their level), reducing the friction Sybil creates.
Increasing user activity and retention across OP Chains by rewarding meaningful on-chain activity with claimable rewards.
Introducing Smart Accounts in a simple yet engaging fashion makes more users and developers aware of the benefits of Smart Accounts.
Through the campaigns, non-DeFi activities can be measured and rewarded across OP Chains.

**What is required to execute this Delegate Mission Request?**
To develop and launch Superchain Accounts, the following milestone need to be completed:

- Phase 1 | Design (~4 weeks): Finalize the technical specification and design of Superchain Accounts.
- Deliverables: Solution document and Prototype.
- Phase 2 | Development (~7 weeks): Develop the required smart contracts, UI components, and documentation, and run various tests.
- Deliverables: Test deployment of Superchain Accounts.
- Phase 3 | Deployment (~3 weeks): Launch the final product after testing and updates.
- Deliverables: Live deployment of Superchain Accounts on Optimism Mainnet with accomplishments fetched from OP Mainnet, Base, and potentially other chains in the Superchain.
- Phase 4 | Program Phase (~4 weeks): Conduct a 1-month-long campaign with weekly raffles to accelerate meaningful participation.
- Deliverables: Campaign plan at the start and results published at the end.
- Phase 5 | Reporting and Iteration (~2 weeks): Complete the Superchain Accounts progress report to be shared with the Optimism Collective and host stakeholder interviews to ideate the following features of Superchain Accounts.
- Deliverables: Superchain Accounts Report with insights and future suggestions published.

**How should the Token House measure progress towards this Mission?**
The Token House should measure progress toward this mission by tracking the completion of each defined milestone within the proposed timeline. Monthly progress reports should be shared on the OP forum to showcase progress.

Additionally, the Token House can evaluate the quality of the design/prototype, code (which should be open-source), and the execution of the campaigns.

**How should badgeholders measure impact upon completion of this Mission?**

A post-mission report should be published, that will cover the following elements that aid badgeholders in evaluating our impact:

User and Transaction Metrics: Insights in the number of Superchain Accounts created, accomplishment badges claimed, number of transactions rewarded, and insights into the transaction volume and retention of Superchain Account users.
Feedback and Community Response: Summary of gathered community and badgeholder feedback and responses.
Season 5 Learnings: The mission recipients learn from building in Season 5.
Future Iterations: Suggestions for the next steps for Superchain Accounts based on the insights from the report.

**Comment by kamescg** [comment]
District Labs recently applied to complete the mission on CharmVerse, but also cross-posting here with critical/questions answers regarding the submission.

We applied with a budget request of 69k OP tokens.

## **What makes you best suited to execute this Mission?**

The District Labs team has extensive experience building web3 products and infrastructure, and is well positioned to build a successful Superchain Account platform. We’ve been building open-source software since our beginning and have been building within the Optimism ecosystem since day one. 

Our mission is to connect the decentralized web, and we believe that Superchain native smart accounts are a great way to progressively onboard users into the Optimism ecosystem with a great consumer experience. By reducing the number of steps required to accomplish any task across the Superchain, we believe that we can bring high quality, sticky users to the Superchain. 

**Relevant Experience:**

We have experience building decentralized identity solutions, onchain prize distributions, and dynamic NFT designs. The District Labs CTO (Kames Geraghty) has spent 8+ years contributing to the Ethereum ecosystem, and championed the deployment of PoolTogether v4 on Optimism, which resulted in one of the most successful incentives campaigns on the Superchain, with over 10,000 DAUs and $40M in peak deposits. 

Our team is well versed in smart contracts, frontend development, backend infrastructure, and open-source projects. Our team has helped shipped several great products and would like to highlight some of our previous work relevant to this RFP:

- Helped lead the deployment of PoolTogether V4 deployment on Optimism, facilitating >$40,000,000 USD in deposits on Optimism, [[link](https://dune.com/queries/1145143/1955031)](https://dune.com/queries/1145143/1955031)
- Drafted the Decentralized Identity System (did:dis) specifications for a scalable smart account identity using decentralized identifiers and verifiable credentials, [[link](https://github.com/decentralized-identity-system)](https://github.com/decentralized-identity-system)
- Contributed to core open source developer infrastructure projects like wagmi and viem, [[link](https://github.com/wevm/wagmi)](https://github.com/wevm/wagmi)

## **What else have you built?**

District Labs most notably built TurboETH, which is a Web3 Application Starter Kit: helping developers quickly built new decentralized applications. We also developed BUIDL, which is a flexible blockchain component library, which supplements TurboETH.

- https://www.turboeth.xyz/
- https://buidl.turboeth.xyz/

In addition to a suite of frontend tools District Labs developed a “smart transactions” i.e. rules and conditions based intents framework. Extending smart accounts with the ability to sign transactions with embedded rules and conditions for how and when they should be executed.

- https://github.com/district-labs/smart-transactions-v0

The smart transaction work stemmed from being early contributors to Delegatable: an object capabilities like framework for transactions with delegatable authority. 

https://github.com/delegatable/delegatable-sol

https://delegatable.org/

As of today District Labs is focused on Emerald. Attempting to answer the question of “How can we onchain millions of users into the SuperChain ecosystem?”

- https://www.emeraldfi.xyz/

Our development/product thesis consists of 3 major phases.

1. Simplify the wallet experience to the most essential elements - everything in 5 clicks or less.
2. Smart accounts to minimize transaction signing requirements - cross-chain execution.
3. Smart transactions to eliminate redundant signing - rules and conditions based intents.

We are applying to complete the “Superchain Account” mission because we feel strongly the research, development and user research embodied within Emerald are the necessary ingredients required to build a successful SuperChain Account experience - today and well into the future.

## **Describe in discrete steps your plan for accomplishing your project:**

We think the “transaction volume and user retention” problem can be split into 3 major areas of focus:

- Reducing the steps to go from incentive to action.
- Encouraging the creation of new habits.
- Eliminating friction associated with completing an action.

And each area of focus can be solved independently.

First and foremost is removing as much complexity as possible from finding a new opportunity and subsequently taking action. 

Second, is rewarding users through incentives and continual high-impact opportunities.

Finally is optimizing for long-term transaction volume and user retention by crafting a Smart Wallet experience that constantly presents high impact opportunities and introduces smart accounts and intent based transactions to eliminate technical friction.

Instead of trying to tackle the problem as a whole, we believe  chances of success will increase significantly if the SuperChain Account challenge is solved in multiple phases.

- Optimize the existing EOA wallet experience. Minimize the amount of steps required to go from incentive to action.
- Introduce smart accounts to increase transaction volume and user retention by minimizing the difficulty of signing transactions to complete meaningful actions.
- Add smart transactions (rules and condition based intents) to automate recurring transactions and reduce signing requirements even further.

Product Phases:

1. Build an application that focuses on the primary EOA wallet experience. Create an Open Source “SuperChain Points” framework. Make points cryptographic signatures and in the future redeemable for gas tokens.
2. Launch a smart account experience that optimizes for taking simultaneous actions on the SuperChain. Focus on cross-chain execution and transaction bundling. Make points redeemable for gas tokens. 
3. Introduce identity primitives, smart transactions (rules and conditions based intents) and integrate these features into wider ecosystem initiatives, campaigns and partnerships.

Evolution & Continues Iteration:

The Emerald codebase will serve as the foundation for creating an Open Source Superchain Account platform. Prioritizing multiple iterations that continually drive value to the Superchain ecosystem as it evolves and matures. And aligning ourselves with the long-term success of reaching critical transaction volume and user retention key performance indictators.

How does this compare to original Mission Request outline of steps to achieve success?

- Phase 1 | Design (~4 weeks)
- Phase 2 | Development (~7 weeks)
- Phase 3 | Deployment (~3 weeks)
- Phase 4 | Program Phase (~4 weeks)
- Phase 5 | Reporting and Iteration (~2 weeks)

From a technical perspective, we believe the 7 week timeline of Phase 2 is aggressive, and ultimately should be sub-divided into multiple development lifecycles.

In our experience, developing secure smart contracts requires many months of focused work, in-depth testing and public audits. Even with the handful of Open Source smart contracts frameworks to choose from, we think it’s worthwhile to take the time to properly evaluate and implement a smart account platform with a strong focus on security and usability.

Excluding the frontend development work, we believe 7 weeks underestimates what’s required to build a secure smart account platform, where the expectation is “incentivizes [for] users to merge their potentially multiple EOA into one account (to increase their level), reducing the friction Sybil creates.” and a protocol/platform that could hold a majority of a user’s assets.

That being said, because we believe the “SuperChain Account” mission can be divided into 3 major phases, with smart account development beginning in phase 2, so it’s still possible have several BIG wins during the initial 7 weeks of development.

As a secure smart account platform is being developed two major features can be rolled out:

1. Open Source Superchain Points Standard
    1. Cryptographically Verifiable Points
    2. Cost-effective distribution using a protocol like [https://witness.co/](https://witness.co/)
    3. Redeemable for gas tokens via ERC-4337
2. Open Source Action Recommendation Engine
    1. Personalized actions/points recommendations
    2. Semantic Web ([[link](https://en.wikipedia.org/wiki/Semantic_Web)](https://en.wikipedia.org/wiki/Semantic_Web)) but for Blockchains i.e. machine readable blockchain data schema to traverse decision trees and to create recommendations for high-impact actions.

From a product perspective, we believe the 4 week timeline of Phase 4 is not aggressive enough.

Changing user habits takes time. Driving meaningful transaction volume requires multiple iterations. Increasing long-term user retention means constantly presenting high-value options.

In the mission request Phase 4 is defined as “a 1-month-long campaign with weekly raffles to accelerate meaningful participation.” which is a great place to start and drive initial interest, but should be continued with recurring campaigns that rely less on “incentives” and more on the “gamification” for completing the highest values action (for your account) on a regular basis.

Most users experience blockchains on 1 of 2 spectrums: DeFi and NFTs.

- Level 1 - DeFi: Hold | NFT: Collect
- Level 2 - DeFi: Trade/Lend | NFT: Engage
- Level 3 - DeFi: Leverage | NFT: Influence
- Level 4 - DeFi: Governance | NFT: Produce

To drive long-term transaction volume and user retention and Superchain Account and Points platform should eventually cater to all user types. First starting with levels 1 and 2, and eventually progressing up the stack to reach levels 3 and 4.

**Off To A Running Start**

As stated in the “**What else have you built?”** question we’re actively building Emerald.

Emerald is the culmination of lots of user research and experiments surrounding smart accounts.

After many months of building prototypes and countless user research interviews, it’s ultimately how we came to our thesis of driving long-term SuperChain adoption.

Solving the adoption problem not only requires the solving difficult technical challenges, but maintaining a keen attention to detail and building a great product experience that progressively onboards through multiple phases of adoption and usage.

As of right now we consider Emerald to be in Phase 1 of the SuperChain development process. We’re actively reducing the number of steps required to go from incentive to action. The core focus is making the EOA wallet experience as seamless as possible for completing high-impact onchain actions.

Emerald will be Open Sourced, regardless of the Optimism grant, and will also be supported through OP funds earned via the TurboETH retroactive public goods grant: we expect to use $30k to $50k over the next 1-6 months for external contributions to the Emerald platform.

It’s important to us, that we build a great Open Source Superchain Account platform, but also foster a strong community of contributors to both the codebase and the product.

**Comment by opjulian** [comment]
This project was selected for this mission request 

https://app.charmverse.io/op-grants/superchain-accounts-wakeup-labs-5137420407693789
