### ISSUE TITLE
🔴 Ecosystem Project Idea: L2 NFT Gift Cards

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#34]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Bridging UX today is a blocker to more people onboarding onto L2s. We’ve heard this especially for NFT users, who tend to be less technical and daring with random interfaces that take their tokens. Gift cards are a great way to get someone into the L2 ecosystem.

From the [Bridge Pass Mirror post](https://d.mirror.xyz/Sjpxa2r_wxkQUGXUr8oO2PhBlyfIRgLBx2YevoXXwyY): 

> *What if we took the gift card metaphor to make collectible NFT editions that, when minted, automatically bridge funds to an L2?*
> 

> Instead of bridging to L2 through a boring “swap” UX, what if users could buy a cool looking NFT! Under the hood, the purchaser receives the collectible NFT on L1, while the funds are bridged and made available on L2.
>

Create a gift card NFT that contains a special note for the recipient and can be redeemed for a certain amount of ETH or OP on OP Mainnet. The gift cards could live either on L1 or on L2.

## Possible Features

- Giftcard marketplace”-like interface, with maybe just a couple of highly desired collections ([motorheadz](https://mirror.xyz/0x57D1eAE9f0972723F0e78EAF4e6C08e90565206F/AtKMzoVY1qzrvA1gal1XqJv74bpx-sg9ptv5TDw2maU)?)
- Allow users to create a gift card by writing a message and attaching some ETH or OP.
- Allow users to send the gift card to addresses on Ethereum or OP Mainnet.
- Allow recipients to access the gift card, see the special message, and redeem the gift card for its value.
- Buy an NFT, autobridge from L1 (or wherever you have funds) 
- If the gift card is sent on Ethereum, redeeming should perform a deposit into OP Mainnet.
- If the gift card is sent on OP Mainnet, redeeming should simply transfer assets to the recipient.

## Impact

- This can onboard new NFT users by just sneaking bridging under the hood.
- It can be a fun way to make OP NFTs go viral — by gifting!

**Comment by abarthell** [comment]
I'll try working on this!

**Comment by smartcontracts** [comment]
@abarthell sick! Let me know if you have any questions

**Comment by abarthell** [comment]
@smartcontracts  Am I on the right track for the [NFT smart contract](https://github.com/abarthell/nft-giftcards/blob/main/contracts/OptimismPass.sol)? (this is my first time using solidity 😄)

Additionally, I have a few questions:
1. Where is [L1StandardBridge.sol](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/L1/messaging/L1StandardBridge.sol) deployed on Eth Mainnet and Goerli? (wasn't able to find the addresses for testing this)
1. [Is this](https://github.com/abarthell/nft-giftcards/blob/main/contracts/OptimismPass.sol#L64-L72) the correct way to call [depositETHTo](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/L1/messaging/L1StandardBridge.sol#L90-L96) from this contract? I was reading about function selectors
1. How do I calculate the l2Gas to pass into [depositETHTo](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/L1/messaging/L1StandardBridge.sol#L90-L96)? Should I use [this from the Optimism SDK](https://github.com/ethereum-optimism/optimism-tutorial/blob/main/sdk-estimate-gas/README.md) on the client side?

Also, if you have another faster way to communicate during this project, do let me know; I'll certainly have some more questions 😄

**Comment by jaymeh13** [comment]
We built a prototype of bridge pass on Maindrop.xyz about a year ago. We didn't see a ton of demand then but maybe we should revisit on OP at some point. ![image](https://github.com/ethereum-optimism/ecosystem-contributions/assets/1761524/7fa3978f-a6d0-449b-8d45-a4ba17257955)

**Comment by 0xV4L3NT1N3** [comment]
Caught my attention while I was scrolling this in Starbucks, here's my implementation on OP Goerli using NFTs as "bridge passes". 

[Try it out](https://l2-gift-interface.vercel.app/) or ping me to send you a pass for 0.25 goETH!

Contract address ( todo verifying it )

https://goerli.etherscan.io/address/0x87554f0f593982a3ca3764dca4e209d68c331d7c

**Comment by abarthell** [comment]
@0xV4L3NT1N3 do you wanna collab on this? I'm also experimenting with account abstraction on the side

**Comment by 0xV4L3NT1N3** [comment]
The contract is verified, source code is open source to be built upon! What do you think account abstraction can help with ?

**Comment by 0xkkonrad** [comment]
# Project Proposal

The Squirrel Labs team would like to build Optimism Giftcards. We will provide an app and SDK for end-users to buy a gift card on mainnet that can be redeemed for oEth and OP. In other words, Alice can send a gift card to Bob, such that Alice pays for it on mainnet with ETH or USDC, and Bob can redeem the equivalent value on optimism in oEth or OP. Alice could be an individual, the Optimism Foundation, or any other party.  

End users create a gift card that contains a special note for the recipient and can be redeemed for a certain amount of ETH or OP on OP Mainnet.

Here is a proposal of how this would work.

To make this work, the following parts are necessary:

- A URL/QR-based gift card mechanism, based on Peanut Protocol
- A bridging mechanism, based on Axelar

![Peanut Protocol Deck 1.0 (1).jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/1a54063f-bbb3-4703-a300-49485b28b051/Peanut_Protocol_Deck_1.0_(1).jpg)

# Gift Card Mechanism

Gift cards should be easy to send. Gift cards have a redeeming mechanism which makes them suitable in scenarios where the recipient’s address is not known. Currently, sending tokens, even on one chain, requires a back-and-forth between Alice and Bob, even if keystore contracts are implemented:

> *Alice: I want to send you $1 on optimism
Bob: How do I check my optimism address? 
Alice: Do you have an EOA or a SC address? 
Bob: I don’t know. I have this thing with the fox.
Alice: Oh, that’s an EOA then. So your address will be the same. Click the fox and copy the long thing starting 0x…
Bob: OK, here it is 0x4f73235220371e3f2dde9c8afc1c310bca7889f3
Alice: OK, I’ve sent you $1 in oEth.
Bob: I don’t see it. How can I check?
Alice: You have to select the Optimism network on MetaMask and then click Assets. Here is the receipt https://optimistic.etherscan.io/tx/0x6ba58320977e5ee8133d9a328e842e4bcb4fd5f5db188cb4723e3a2345d8b4d2 
Bob: This is hard. I don’t want to bother you anymore, so I will read some tutorials on how to do this next week.
* Bob might or might not be converted to an Optimism user **
> 

Instead, we propose a gift card mechanism that relies on claiming tokens from a QR code or token. In other words, Alice deposits funds and sends a URL or QR that lets Bob withdraw the funds. The frontend ensures that Bob is connected to Optimism and adds Optimism if it has not been added. In effect, here is what gifting tokens this would look like this:

> *Alice: I am sending you $1 in oEth to get you started on Optimism https://peanut.to/claim?c=opt&v=v3&i=1401&p=5MagiC6PZq2Dwrp7 **
> 
> 
> *Bob: Ok, thanks! 🐿️*
> 

## How does it work?

So how does it work? The link is simply a user-friendly way of sending an off-chain message. All it is an array of parameters: For instance this Peanut link `https://peanut.to/claim?c=3&v=v3&i=1251&p=twLDK7YWL9tOZi9A` is actually just a medium for the following information:

```
{
  "chain-id": 3,
  "version": "v3",
  "transfer-id": 1251,
  "secret": "twLDK7YWL9tOZi9A"
}
```

The claim function on the frontend then ensures that that this array is relayed to an RPC.

### **Why links?**

If it’s just an array of data, why use links? Because links will have a frontend that will deliver the JSON to the right place. Without such a frontend, each app would have to integrate a receive and send functionality within their app. URLs are already compatible with all devices, dapps, messengers and wallets without requiring any integration. The crazy thing is: everyone with internet access can already use this cutting-edge decentralised protocol called HTTPS, without any onboarding. This means links are compatible with a web2 audience too. In such a case, the frontend can guide a crypto newbie through the onboarding process, which with account abstraction will be a few clicks.

# Bridging with Axelar and Squid

Alice should be able to buy a gift card on mainnet that can be redeemed on Optimism by Bob.

To do this, funds are deposited into Peanut Protocol on mainnet and then bridged to oEth on Optimism using Axelar and Squid. That is, Alice deposits $1 in Eth to Peanut Protocol on mainnet, and sends the gift card to Bob. As soon as Bob connects his wallet and reveals his Optimism wallet address, the mainnet Peanut Protocol smart contract routes the funds to Squid for bridging. Bob can click claim and no further action is required. The release of the funds will be triggered and gas will be paid by a paymaster from a gas pool for optimism onboarding. 

Keep in mind that Alice and Bob could be the same person, making this useful also for onboarding oneself, rather than others.

# Additional Features in the Future

- Tokens on many chains can be used to buy the gift card. I.e. Alice can deposit funds from Polygon or even use USDC.
- OP is added as destination token.
- The gift card comes with a special note (a message and an image hosted on IPFS).

# Contact
Optimism folks, if you're interested, let's chat some more! @0xkkonrad or mail konrad at peanut.to

**Comment by 0xkkonrad** [comment]
@smartcontracts lmk whether it makes sense to do this!

**Comment by dimsome** [comment]
@0xkkonrad I've been experimenting with a similiar concept, how far along are you?

**Comment by 0xkkonrad** [comment]
we're live :)
