### ISSUE TITLE
🔴 Ecosystem Project Idea: Community RPGF Signup Form 

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#84]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The RetroPGF grant process has changed for Round 3, now requiring teams to self-nominate. This shift could potentially leave out projects that are not aware of the process or the opportunity. To bridge this gap, we propose the creation of a public nomination form that anyone can fill out to nominate projects. The results of this form can be made available on a public read-only spreadsheet. This would allow teams to review community nominations and reach out to promising projects that might otherwise be overlooked.

Note: The RetroPGF sign-up itself is being build by the OP Labs EcoPod team and will go live in the coming months. This Project Idea's sole focus is a form for the community to suggest projects that should sign-up

**OP Labs or Optimism Foundation Contact**: Jonas (gh: @JSeiferth, TG/Discord: @jonassft)

## Possible Features

- The form should be easy to fill out and provide clear instructions to guide nominators.
- It should include specific fields designed to capture as much relevant information about the nominated project as possible.
- The results of the form submissions should be automatically populated to a public read-only spreadsheet.
- To prevent the influx of spammy entries, consider implementing basic form validation and moderation features.

## Impact

- It can help identify projects that might not be aware of RetroPGF and provide them with the opportunity to participate.
- The publicly available spreadsheet of nominations can serve as a valuable resource for teams, giving them the ability to review and reach out to nominated projects.
- This process could increase the pool of eligible projects for RetroPGF, resulting in a more diverse and inclusive grant process.

**Comment by Billy19191** [comment]
Interesting, I will try to build it up. 1 Question, Do I need to self-host or it will be merged with Optimism.io later on?

**Comment by sergeybruska** [comment]
Hey, everyone 👋️️️️️️
I am pleased to share with you the news that we have created a RetroPGF project nomination form. This form provides a convenient way to apply for a grant and view the list of nominees. Functionality is provided to moderate projects for spam/scam. 

**Demo**
https://retropgfnominate.xyz/

**Login page**
https://retropgfnominate.xyz/login
testadmin@test.com / Testadmin1234@

**Comment by JSeiferth** [comment]
Hey @sergeybruska! 
Thank you for taking the initiative on this, the site looks pretty slick!

Important to clarify that this Project Idea is for the community to be able to **suggest projects that should sign-up for RetroPGF**.
> The RetroPGF grant process has changed for Round 3, now requiring teams to self-nominate. This shift could potentially leave out projects that are not aware of the process or the opportunity. To bridge this gap, we propose the creation of a public nomination form that anyone can fill out to nominate projects.

Your form currently suggests that projects themselves should use https://retropgfnominate.xyz/ to sign-up for RetroPGF. 
> Tell the community RetroPGF about your project and how it will be useful, so you increase the likelihood of getting grants

The purpose of this form would be for the community to suggest projects that they think should sign-up. This information will then be used to notify projects about signing up. The RetroPGF sign-up form for projects is being built by the OP Labs Ecopod team and will go live in the coming months. 

Sorry if this wasn't obvious, I'll update the text of the project idea to reflect this more clearly.

I would suggest to change the copy on the landing page to clarify that this is for the community to suggest projects that should sign-up and that the sign-up itself will go live at https://app.optimism.io/retropgf in the coming months.

**Comment by Billy19191** [comment]
**Hello everyone!**, my name is Billy and I am one of the Support-NERDs and an Ambassador for the Optimism Collective. You may have seen me on Twitter or Discord. I am currently working with @wit03 on the RetroPGF Dashboard which include the community sign-up form for RetroPGF round 3. Beyond that, this platform will display all projects that was nominated by community as public info that and reach out to promising projects that might otherwise be overlooked.

We are thrilled to announce the upcoming launch of the RetroPFG Hub. This platform will allow users and the community to discover more about RetroPGF of Optimism. You can find the repository for our dashboard/project at [here](https://github.com/FWB-Creators/RetroPGF-Hub) and demo site [here](http://retro-pgf-hub.vercel.app) (http://retro-pgf-hub.vercel.app)

Please note that our website is still in development, but it will be completed by the end of this month. We will share the proper link (domain) as soon as it is publicly launched.

<img width="1859" alt="Screenshot 2023-09-15 at 00 17 17" src="https://github.com/ethereum-optimism/ecosystem-contributions/assets/27849965/961143af-c977-427f-8010-bd9bd525165a">
